[project]
name = 'Truthdrop'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.Truthdrop]
path = 'contracts/Truthdrop.clar'
clarity_version = 3
epoch = 3.1
[contracts.disclosure-impact-tracker]
path = 'contracts/disclosure-impact-tracker.clar'
clarity_version = 3
epoch = 3.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
